apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: combined-monorepo
  description: All our components represented as a monorepo
  annotations:
    github.com/project-slug: dezkareid/dummy-utils
spec:
  type: service
  owner: engineering
  lifecycle: production